version: '2.4'
services:
  # 1. Ваш User Service (использует ваш Dockerfile)
  user-service:
    build: ./services/health_check  # Папка, где находится main.go и Dockerfile
    container_name: user_service
    restart: "no"
    ports:
      - "8080:8080"
